class BaseLogic:
    async def get_by_id(self, entity_id: int):
        ...

    async def get_all(self):
        ...

    async def create(self, data: dict):
        ...

    async def update(self, entity_id: int, data: dict):
        ...

    async def delete(self, entity_id: int):
        ...